tested & fixed issue for API integration for upcoming events
ooug/admin pull request #21
Opened 2021-04-14 16:39 UTC by avinashvidyarthi

2021-04-15 01:50 UTC, InSantoshMahto commented on src/environments/environment.ts
> +  server: 'http://localhost:3000',
use / at end **http://localhost:3000/**

2021-04-15 01:56 UTC, InSantoshMahto requested changes
forget about what we did earlier just use camel case for all type of data we store in collections.

```javascript
# Example

# Currently
const payload = {
Date: {month: 1, day: 1, year:2020}
}

# What We Wanted
const payload = {
date: {month: 1, day: 1, year:2020}
}
```

2021-04-15 01:57 UTC, InSantoshMahto commented
If minor change iss required to do in backend we will do that.

2021-04-16 04:48 UTC, avinashvidyarthi commented
Variable camelCasing done. Minor changes in backend too

2021-04-17 17:56 UTC, InSantoshMahto approved these changes

2021-04-17 17:57 UTC, merged